name: Deploy to Heroku

on:
  push:
    branches: [master]

jobs:
  Deploy:
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "aboutcert"
        heroku_email: "nomsouzoanya@yahoo.co.uk"

    - name: Run a one-line script
      run: git push heroku